### ISSUE TITLE
Broken PDF links section usage on main page

### ISSUE THREAD

**Issue by grimson73** [zeld/psa-update#11]
Hi,
Unfortunately, the links to the instructions PDFs are broken
https://github.com/zeld/psa-update?tab=readme-ov-file#usage

For Opel I obtained this instruction (after running 'Opel Update', guess it would apply to all PSA NAC systems)
https://www.opel.com/content/dam/opel/OpelCorporate/nac/update-instructions_EN.pdf

**Comment by zeld** [comment]
Indeed, thanks for noticing. English versions seem to have disappeared from Peugeot website... I was able to find Citroen version for NAC as well: https://www.citroen.co.uk/content/dam/citroen/master/citroenupdate/Citroen-user-manual_NAC_EN.pdf

**Comment by zeld** [comment]
Fixed link by referring to archived versions on internet archive:

- https://web.archive.org/web/20220719220945/https://media-ct-ndp.peugeot.com/file/38/2/map-software-rcc-en.632382.pdf
- https://web.archive.org/web/20230602131011/https://media-ct-ndp.peugeot.com/file/38/0/map-software-nac-en.632380.pdf

Thanks again.
