### ISSUE TITLE
Feature Request: Format USB Before Extracting Files

### ISSUE THREAD

**Issue by LucaBarbaLata** [zeld/psa-update#12]
I have a 64 gb usb stick and i cant format it to FAT32 with the explorer or disk management. it would be cool to format the usb drive for you and then initialize the extract process

**Comment by zeld** [comment]
Hi, I'm not sure I'm willing to bring this into the tool as it would need administration privileges to run. Also I don't know if there are suitable cross platform implementations in rust at the moment...

Why exactly are you not able to format your USB drive from Windows?

**Comment by LucaBarbaLata** [comment]
Normally in windows you cannot format in FAT32 a storage device that has over 32 GB Capacity. I tried using tools online but with no result. I ended up making a partition with 32 then formatted it into FAT32 and copied the files. Although I didn't tested it because im skeptical about it. So i haven't tested it yet 
 
 
 
 
 
 
 
 
 Hi, I'm not sure I'm willing to bring this into the tool as it would need administration privileges to run. Also I don't know if there are suitable implementation in rust... 
 Why exactly are you not able to format your USB drive from Windows?

**Comment by zeld** [comment]
Indeed, from what I read it is not possible to format 64 GB drives using FAT32 with explorer or drive tool. But it seems to be possible using `format` from command line: `format /FS:FAT32 D:` where `D:` is the drive letter. Did you try this?

If it works I can add a word about it in the README.

Edit: I also read that `format` is not able to go beyond 32 GB... Looks like official update application embeds`fat32format` from http://ridgecrop.co.uk/index.htm?guiformat.htm

**Comment by LucaBarbaLata** [comment]
Il give it a try and come back with a response. 
 
 Thanks 👍  
 
 
 
 
 
 
 
 
 Indeed, from what I read it is not possible to format 64 GB drives using FAT32 with explorer or drive tool. But it seems to be possible using  format  from command line:  format /FS:FAT32 D:  where  D:  is the drive letter. Did you try this? 
 If it works I can add a word about it in the README.

**Comment by LucaBarbaLata** [comment]
Oh i just saw your edit after i tried it. well yeah it failed ofc. but would it be fine if i made a partition and thats all (32 gb)
it should work like normal as far as i know. what do you think?

**Comment by zeld** [comment]
I think it should be OK to create a 32 GB FAT32 partition on the 64 GB device. Worst case scenario here is that the car does not recognize the device, and will not be able to detect update files.

Alternatively I expect the fat32format to be able to format a 64 GB partition as this is the tool that is used by the official vendor application.

**Comment by zeld** [comment]
I updated the README with USB drive prerequisites and would be interested by your feedback.

Then, since I'm not planning to bring this feature into the tool as mentioned earlier, I'll close this issue.

**Comment by LucaBarbaLata** [comment]
the README is great. i will type here if the partition method worked because i will try it in this weekend (although it should work with no problems but just in case) and then you may close this!! Thanks. 😊

**Comment by LucaBarbaLata** [comment]
It worked!!

**Comment by zeld** [comment]
Cool, thanks for the update!
